env: 'local'
port: ':7777'
server:
  address: 'localhost:7777'
  timeout: 4s
  iddle_timeout: 60s

log-level: 'debug'

database_url: 'host=localhost port=5432 user=postgres password=admin dbname=postgres sslmode=disable'